/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessRouteImport } from './routes/access'
import { Route as BankAccountsRouteImport } from './routes/bank-accounts'
import { Route as CashRouteImport } from './routes/cash'
import { Route as ExpectedRouteImport } from './routes/expected'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as FacilityHistoryRouteImport } from './routes/facility-history'
import { Route as FacilityListRouteImport } from './routes/facility-list'
import { Route as FacilityTransactionsRouteImport } from './routes/facility-transactions'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as ApiDataAppAccessRouteImport } from './routes/api/data/app-access'
import { Route as ApiDataBankAccountsRouteImport } from './routes/api/data/bank-accounts'
import { Route as ApiDataCashRouteImport } from './routes/api/data/cash'
import { Route as ApiDataExpectedRouteImport } from './routes/api/data/expected'
import { Route as ApiDataFacilitiesRouteImport } from './routes/api/data/facilities'
import { Route as ApiDataFacilityLcAmendmentsRouteImport } from './routes/api/data/facility-lc-amendments'
import { Route as ApiDataFacilityTransactionsRouteImport } from './routes/api/data/facility-transactions'
import { Route as ApiDataFacilityTransactionsSettleRouteImport } from './routes/api/data/facility-transactions.settle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const BankAccountsRoute = BankAccountsRouteImport.update({
  id: '/bank-accounts',
  path: '/bank-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const CashRoute = CashRouteImport.update({
  id: '/cash',
  path: '/cash',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpectedRoute = ExpectedRouteImport.update({
  id: '/expected',
  path: '/expected',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilityHistoryRoute = FacilityHistoryRouteImport.update({
  id: '/facility-history',
  path: '/facility-history',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilityListRoute = FacilityListRouteImport.update({
  id: '/facility-list',
  path: '/facility-list',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilityTransactionsRoute = FacilityTransactionsRouteImport.update({
  id: '/facility-transactions',
  path: '/facility-transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataAppAccessRoute = ApiDataAppAccessRouteImport.update({
  id: '/api/data/app-access',
  path: '/api/data/app-access',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataBankAccountsRoute = ApiDataBankAccountsRouteImport.update({
  id: '/api/data/bank-accounts',
  path: '/api/data/bank-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataCashRoute = ApiDataCashRouteImport.update({
  id: '/api/data/cash',
  path: '/api/data/cash',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataExpectedRoute = ApiDataExpectedRouteImport.update({
  id: '/api/data/expected',
  path: '/api/data/expected',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataFacilitiesRoute = ApiDataFacilitiesRouteImport.update({
  id: '/api/data/facilities',
  path: '/api/data/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataFacilityLcAmendmentsRoute =
  ApiDataFacilityLcAmendmentsRouteImport.update({
    id: '/api/data/facility-lc-amendments',
    path: '/api/data/facility-lc-amendments',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDataFacilityTransactionsRoute =
  ApiDataFacilityTransactionsRouteImport.update({
    id: '/api/data/facility-transactions',
    path: '/api/data/facility-transactions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDataFacilityTransactionsSettleRoute =
  ApiDataFacilityTransactionsSettleRouteImport.update({
    id: '/settle',
    path: '/settle',
    getParentRoute: () => ApiDataFacilityTransactionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/bank-accounts': typeof BankAccountsRoute
  '/cash': typeof CashRoute
  '/expected': typeof ExpectedRoute
  '/facilities': typeof FacilitiesRoute
  '/facility-history': typeof FacilityHistoryRoute
  '/facility-list': typeof FacilityListRoute
  '/facility-transactions': typeof FacilityTransactionsRoute
  '/transactions': typeof TransactionsRoute
  '/api/data/app-access': typeof ApiDataAppAccessRoute
  '/api/data/bank-accounts': typeof ApiDataBankAccountsRoute
  '/api/data/cash': typeof ApiDataCashRoute
  '/api/data/expected': typeof ApiDataExpectedRoute
  '/api/data/facilities': typeof ApiDataFacilitiesRoute
  '/api/data/facility-lc-amendments': typeof ApiDataFacilityLcAmendmentsRoute
  '/api/data/facility-transactions': typeof ApiDataFacilityTransactionsRouteWithChildren
  '/api/data/facility-transactions/settle': typeof ApiDataFacilityTransactionsSettleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/bank-accounts': typeof BankAccountsRoute
  '/cash': typeof CashRoute
  '/expected': typeof ExpectedRoute
  '/facilities': typeof FacilitiesRoute
  '/facility-history': typeof FacilityHistoryRoute
  '/facility-list': typeof FacilityListRoute
  '/facility-transactions': typeof FacilityTransactionsRoute
  '/transactions': typeof TransactionsRoute
  '/api/data/app-access': typeof ApiDataAppAccessRoute
  '/api/data/bank-accounts': typeof ApiDataBankAccountsRoute
  '/api/data/cash': typeof ApiDataCashRoute
  '/api/data/expected': typeof ApiDataExpectedRoute
  '/api/data/facilities': typeof ApiDataFacilitiesRoute
  '/api/data/facility-lc-amendments': typeof ApiDataFacilityLcAmendmentsRoute
  '/api/data/facility-transactions': typeof ApiDataFacilityTransactionsRouteWithChildren
  '/api/data/facility-transactions/settle': typeof ApiDataFacilityTransactionsSettleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/bank-accounts': typeof BankAccountsRoute
  '/cash': typeof CashRoute
  '/expected': typeof ExpectedRoute
  '/facilities': typeof FacilitiesRoute
  '/facility-history': typeof FacilityHistoryRoute
  '/facility-list': typeof FacilityListRoute
  '/facility-transactions': typeof FacilityTransactionsRoute
  '/transactions': typeof TransactionsRoute
  '/api/data/app-access': typeof ApiDataAppAccessRoute
  '/api/data/bank-accounts': typeof ApiDataBankAccountsRoute
  '/api/data/cash': typeof ApiDataCashRoute
  '/api/data/expected': typeof ApiDataExpectedRoute
  '/api/data/facilities': typeof ApiDataFacilitiesRoute
  '/api/data/facility-lc-amendments': typeof ApiDataFacilityLcAmendmentsRoute
  '/api/data/facility-transactions': typeof ApiDataFacilityTransactionsRouteWithChildren
  '/api/data/facility-transactions/settle': typeof ApiDataFacilityTransactionsSettleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/bank-accounts'
    | '/cash'
    | '/expected'
    | '/facilities'
    | '/facility-history'
    | '/facility-list'
    | '/facility-transactions'
    | '/transactions'
    | '/api/data/app-access'
    | '/api/data/bank-accounts'
    | '/api/data/cash'
    | '/api/data/expected'
    | '/api/data/facilities'
    | '/api/data/facility-lc-amendments'
    | '/api/data/facility-transactions'
    | '/api/data/facility-transactions/settle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/bank-accounts'
    | '/cash'
    | '/expected'
    | '/facilities'
    | '/facility-history'
    | '/facility-list'
    | '/facility-transactions'
    | '/transactions'
    | '/api/data/app-access'
    | '/api/data/bank-accounts'
    | '/api/data/cash'
    | '/api/data/expected'
    | '/api/data/facilities'
    | '/api/data/facility-lc-amendments'
    | '/api/data/facility-transactions'
    | '/api/data/facility-transactions/settle'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/bank-accounts'
    | '/cash'
    | '/expected'
    | '/facilities'
    | '/facility-history'
    | '/facility-list'
    | '/facility-transactions'
    | '/transactions'
    | '/api/data/app-access'
    | '/api/data/bank-accounts'
    | '/api/data/cash'
    | '/api/data/expected'
    | '/api/data/facilities'
    | '/api/data/facility-lc-amendments'
    | '/api/data/facility-transactions'
    | '/api/data/facility-transactions/settle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  BankAccountsRoute: typeof BankAccountsRoute
  CashRoute: typeof CashRoute
  ExpectedRoute: typeof ExpectedRoute
  FacilitiesRoute: typeof FacilitiesRoute
  FacilityHistoryRoute: typeof FacilityHistoryRoute
  FacilityListRoute: typeof FacilityListRoute
  FacilityTransactionsRoute: typeof FacilityTransactionsRoute
  TransactionsRoute: typeof TransactionsRoute
  ApiDataAppAccessRoute: typeof ApiDataAppAccessRoute
  ApiDataBankAccountsRoute: typeof ApiDataBankAccountsRoute
  ApiDataCashRoute: typeof ApiDataCashRoute
  ApiDataExpectedRoute: typeof ApiDataExpectedRoute
  ApiDataFacilitiesRoute: typeof ApiDataFacilitiesRoute
  ApiDataFacilityLcAmendmentsRoute: typeof ApiDataFacilityLcAmendmentsRoute
  ApiDataFacilityTransactionsRoute: typeof ApiDataFacilityTransactionsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-accounts': {
      id: '/bank-accounts'
      path: '/bank-accounts'
      fullPath: '/bank-accounts'
      preLoaderRoute: typeof BankAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash': {
      id: '/cash'
      path: '/cash'
      fullPath: '/cash'
      preLoaderRoute: typeof CashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expected': {
      id: '/expected'
      path: '/expected'
      fullPath: '/expected'
      preLoaderRoute: typeof ExpectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facility-history': {
      id: '/facility-history'
      path: '/facility-history'
      fullPath: '/facility-history'
      preLoaderRoute: typeof FacilityHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facility-list': {
      id: '/facility-list'
      path: '/facility-list'
      fullPath: '/facility-list'
      preLoaderRoute: typeof FacilityListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facility-transactions': {
      id: '/facility-transactions'
      path: '/facility-transactions'
      fullPath: '/facility-transactions'
      preLoaderRoute: typeof FacilityTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data/app-access': {
      id: '/api/data/app-access'
      path: '/api/data/app-access'
      fullPath: '/api/data/app-access'
      preLoaderRoute: typeof ApiDataAppAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data/bank-accounts': {
      id: '/api/data/bank-accounts'
      path: '/api/data/bank-accounts'
      fullPath: '/api/data/bank-accounts'
      preLoaderRoute: typeof ApiDataBankAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data/cash': {
      id: '/api/data/cash'
      path: '/api/data/cash'
      fullPath: '/api/data/cash'
      preLoaderRoute: typeof ApiDataCashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data/expected': {
      id: '/api/data/expected'
      path: '/api/data/expected'
      fullPath: '/api/data/expected'
      preLoaderRoute: typeof ApiDataExpectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data/facilities': {
      id: '/api/data/facilities'
      path: '/api/data/facilities'
      fullPath: '/api/data/facilities'
      preLoaderRoute: typeof ApiDataFacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data/facility-lc-amendments': {
      id: '/api/data/facility-lc-amendments'
      path: '/api/data/facility-lc-amendments'
      fullPath: '/api/data/facility-lc-amendments'
      preLoaderRoute: typeof ApiDataFacilityLcAmendmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data/facility-transactions': {
      id: '/api/data/facility-transactions'
      path: '/api/data/facility-transactions'
      fullPath: '/api/data/facility-transactions'
      preLoaderRoute: typeof ApiDataFacilityTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data/facility-transactions/settle': {
      id: '/api/data/facility-transactions/settle'
      path: '/settle'
      fullPath: '/api/data/facility-transactions/settle'
      preLoaderRoute: typeof ApiDataFacilityTransactionsSettleRouteImport
      parentRoute: typeof ApiDataFacilityTransactionsRoute
    }
  }
}

interface ApiDataFacilityTransactionsRouteChildren {
  ApiDataFacilityTransactionsSettleRoute: typeof ApiDataFacilityTransactionsSettleRoute
}

const ApiDataFacilityTransactionsRouteChildren: ApiDataFacilityTransactionsRouteChildren =
  {
    ApiDataFacilityTransactionsSettleRoute:
      ApiDataFacilityTransactionsSettleRoute,
  }

const ApiDataFacilityTransactionsRouteWithChildren =
  ApiDataFacilityTransactionsRoute._addFileChildren(
    ApiDataFacilityTransactionsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  BankAccountsRoute: BankAccountsRoute,
  CashRoute: CashRoute,
  ExpectedRoute: ExpectedRoute,
  FacilitiesRoute: FacilitiesRoute,
  FacilityHistoryRoute: FacilityHistoryRoute,
  FacilityListRoute: FacilityListRoute,
  FacilityTransactionsRoute: FacilityTransactionsRoute,
  TransactionsRoute: TransactionsRoute,
  ApiDataAppAccessRoute: ApiDataAppAccessRoute,
  ApiDataBankAccountsRoute: ApiDataBankAccountsRoute,
  ApiDataCashRoute: ApiDataCashRoute,
  ApiDataExpectedRoute: ApiDataExpectedRoute,
  ApiDataFacilitiesRoute: ApiDataFacilitiesRoute,
  ApiDataFacilityLcAmendmentsRoute: ApiDataFacilityLcAmendmentsRoute,
  ApiDataFacilityTransactionsRoute:
    ApiDataFacilityTransactionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
